# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: test
  demands:
    - agent.name -equals test

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: '184.73.24.206'
    username: 'Administrator'
    password: 'p&y''6)Nr<Gc4'
    rootDirectory: '/hello'
    filePatterns: '**'
    remoteDirectory: '/upload/$(Build.BuildId)/'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false